# Automatically close issues or pull requests that have a label, after a custom delay, if no one replies.
# https://github.com/tiangolo/issue-manager

name: Issue Manager

on:
  # Every day at 2:36am
  schedule:
    - cron: '36 2 * * *'

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: tiangolo/issue-manager@0.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          config: >
            {
              "answered": {
                "message": "Assuming the question was answered, this will be automatically closed now."
              },
              "solved": {
                "message": "Assuming the original issue was solved, it will be automatically closed now."
              },
              "waiting": {
                "message": "Automatically closing after waiting for additional info. To re-open, please provide the additional information requested."
              }
            }
